data_path: data
allow_file_type : [".txt", ".pdf"]
md5_hex_store: md5.txt


collection_name: agent
persist_directory: chroma_db

chunk_size: 400
chunk_overlap: 20
top_k: 6
separators: ["\n\n","。",".","?","？","!"," ",""]